_VPATH	+=:$(ROOT)/wrapper

LIBOBJ  += mchp_fft16.o
LIBOBJ  += mchp_fft32.o
LIBOBJ  += mchp_fir.o
LIBOBJ  += mchp_inittwid16.o
LIBOBJ  += mchp_inittwid32.o
LIBOBJ  += mchp_vadd16.o
LIBOBJ  += mchp_vadd32.o
LIBOBJ  += mchp_vdot16.o
LIBOBJ  += mchp_vdot32.o
LIBOBJ  += mchp_vmul16.o
LIBOBJ  += mchp_vmul32.o
LIBOBJ  += mchp_vpow16.o
LIBOBJ  += mchp_vpow32.o
LIBOBJ  += mchp_vscl16.o
LIBOBJ  += mchp_vscl32.o
LIBOBJ  += mchp_vsub16.o
LIBOBJ  += mchp_vsub32.o

